version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - misspell
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
    gocritic:
      disabled-checks:
        - hugeParam
        - rangeValCopy
        - unnamedResult
      enabled-tags:
        - performance
        - diagnostic
        - style
        - experimental
        - opinionated
    staticcheck:
      checks:
        - all
        - -SA1019
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - hack
      - docs
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - sigs.k8s.io/krew
  exclusions:
    generated: lax
    paths:
      - hack
      - docs
      - third_party$
      - builtin$
      - examples$
