# all available settings of specific linters
linters-settings:
  gocritic:
    enabled-tags:
      - performance
      - diagnostic
      - style
      - experimental
      - opinionated
    disabled-checks:
      - hugeParam
      - rangeValCopy
      - unnamedResult
  gofmt:
    simplify: true
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: sigs.k8s.io/krew
  errcheck:
    check-type-assertions: false
    check-blank: false
  staticcheck:
    checks:
    - all
    - "-SA1019" # allow usage of global rand.Seed


# options for analysis running
run:
  # include test files
  tests: true

issues:
  # which dirs to skip: they won't be analyzed;
  # can use regexp here: generated.*, regexp is applied on full path;
  # default value is empty list, but next dirs are always skipped independently
  # from this option's value:
  #   	vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  exclude-dirs:
    - hack
    - docs

linters:
  disable-all: true
  enable:
    - errcheck
    - gocritic
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
