#!/usr/bin/env bash
#
# Install krew
#
# License: Apache 2.0 - see https://github.com/kubernetes-sigs/krew/blob/master/LICENSE

set -o pipefail
set -o errexit

STABLE_RELEASE="$(cat $(dirname $0)/STABLE_RELEASE)"

(
  cd "$(mktemp -d)" &&
  curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/download/${STABLE_RELEASE}/krew.{tar.gz,yaml}" &&
  tar zxvf krew.tar.gz &&
  KREW=./krew-"$(uname | tr '[:upper:]' '[:lower:]')_amd64" &&
  "$KREW" install --manifest=krew.yaml --archive=krew.tar.gz &&
  "$KREW" update
)
