apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: krew
spec:
  version: "KREW_TAG"
  homepage: https://krew.sigs.k8s.io/
  shortDescription: Package manager for kubectl plugins.
  caveats: |
    krew is now installed! To start using kubectl plugins, you need to add
    krew's installation directory to your PATH:

      * macOS/Linux:
        - Add the following to your ~/.bashrc or ~/.zshrc:
            export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
        - Restart your shell.

      * Windows: Add %USERPROFILE%\.krew\bin to your PATH environment variable

    To list krew commands and to get help, run:
      $ kubectl krew
    For a full list of available plugins, run:
      $ kubectl krew search

    You can find documentation at
      https://krew.sigs.k8s.io/docs/user-guide/quickstart/.

  # The supported platforms for plugins are the ones that Krew itself is distributed in.
  # See all supported platforms on the [releases page](https://github.com/kubernetes-sigs/krew/releases).
  platforms:
  - uri: https://github.com/kubernetes-sigs/krew/releases/download/KREW_TAG/krew-darwin_amd64.tar.gz
    sha256: KREW_DARWIN_AMD64_CHECKSUM
    bin: krew
    files:
    - from: ./krew-darwin_amd64
      to: krew
    - from: ./LICENSE
      to: .
    selector:
      matchLabels:
        os: darwin
        arch: amd64
  - uri: https://github.com/kubernetes-sigs/krew/releases/download/KREW_TAG/krew-darwin_arm64.tar.gz
    sha256: KREW_DARWIN_ARM64_CHECKSUM
    bin: krew
    files:
    - from: ./krew-darwin_arm64
      to: krew
    - from: ./LICENSE
      to: .
    selector:
      matchLabels:
        os: darwin
        arch: arm64
  - uri: https://github.com/kubernetes-sigs/krew/releases/download/KREW_TAG/krew-linux_amd64.tar.gz
    sha256: KREW_LINUX_AMD64_CHECKSUM
    bin: krew
    files:
    - from: ./krew-linux_amd64
      to: krew
    - from: ./LICENSE
      to: .
    selector:
      matchLabels:
        os: linux
        arch: amd64
  - uri: https://github.com/kubernetes-sigs/krew/releases/download/KREW_TAG/krew-linux_arm.tar.gz
    sha256: KREW_LINUX_ARM_CHECKSUM
    bin: krew
    files:
    - from: ./krew-linux_arm
      to: krew
    - from: ./LICENSE
      to: .
    selector:
      matchLabels:
        os: linux
        arch: arm
  - uri: https://github.com/kubernetes-sigs/krew/releases/download/KREW_TAG/krew-linux_arm64.tar.gz
    sha256: KREW_LINUX_ARM64_CHECKSUM
    bin: krew
    files:
    - from: ./krew-linux_arm64
      to: krew
    - from: ./LICENSE
      to: .
    selector:
      matchLabels:
        os: linux
        arch: arm64
  - uri: https://github.com/kubernetes-sigs/krew/releases/download/KREW_TAG/krew-linux_ppc64le.tar.gz
    sha256: KREW_LINUX_PPC64LE_CHECKSUM
    bin: krew
    files:
    - from: ./krew-linux_ppc64le
      to: krew
    - from: ./LICENSE
      to: .
    selector:
      matchLabels:
        os: linux
        arch: ppc64le
  - uri: https://github.com/kubernetes-sigs/krew/releases/download/KREW_TAG/krew-windows_amd64.tar.gz
    sha256: KREW_WINDOWS_AMD64_CHECKSUM
    bin: krew.exe
    files:
    - from: ./krew-windows_amd64.exe
      to: krew.exe
    - from: ./LICENSE
      to: .
    selector:
      matchLabels:
        os: windows
        arch: amd64
